# frozen_string_literal: true

source 'https://rubygems.org'

# force ssl to fetch from github
git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'fast_gettext', '~> 2.2'
